# Database Configuration
db.url=jdbc:h2:file:./data/storagedb;DB_CLOSE_DELAY=-1
db.username=sa
db.password=password

# Session ttl
session.ttl.minutes=1440

#CacheStorageService
cache.max.memory=104857600
cache.max.memory.policy=ALLKEYSLRU
cache.persistence=false